version: '3'

networks:
  monitoring:

services:
  :
    environment:
      - VERACODE_API_KEY_ID=${VERACODE_API_KEY_ID}
      - VERACODE_API_KEY_SECRET=${VERACODE_API_KEY_SECRET}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.30.3
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - monitoring

  grafana:
      image: grafana/grafana
      user: "472"
      depends_on:
        - prometheus
      environment: 
        GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
        GF_AUTH_ANONYMOUS_ENABLED: "true"
        GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
        GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
        GF_AUTH_DISABLE_LOGIN_FORM: "true"
      volumes:
        - ./veracode-grafana-dashboard.json:/var/lib/grafana/dashboards/veracode-grafana-dashboard.json
        - ./local.yml:/etc/grafana/provisioning/dashboards/local.yml
        - ./prometheus_ds.yml:/etc/grafana/provisioning/datasources/prometheus_ds.yml
      ports:
        - 3000:3000
      networks:
        - monitoring